In [50]:
import scipy
import numpy as np
import pandas as pd

In [51]:
# random sparse matrix with shape 100,000 x 90,000
dummy = scipy.sparse.random(4, 4, density=0.5, format='csr')

In [52]:
# %%timeit
b = dummy.tocsr()
np.split(b.indices, b.indptr[1:-1])

[array([0, 1], dtype=int32),
 array([0, 1], dtype=int32),
 array([2], dtype=int32),
 array([1, 2, 3], dtype=int32)]

In [53]:
# %%timeit
connected_constraints = [
    b[i, :].nonzero()[1].tolist()
    for i in range(b.shape[0])
]

In [54]:
print(b.toarray())

[[0.71803898 0.75373094 0.         0.        ]
 [0.4511002  0.94146668 0.         0.        ]
 [0.         0.         0.95508763 0.        ]
 [0.         0.35833639 0.921038   0.0274011 ]]


In [55]:
b.indices

array([0, 1, 0, 1, 2, 1, 2, 3], dtype=int32)

In [56]:
b.indptr

array([0, 2, 4, 5, 8], dtype=int32)

In [57]:
b.data[b.indptr[0]:b.indptr[1]]

array([0.71803898, 0.75373094])

In [58]:
degrees = np.diff(b.indptr)

In [59]:
np.mean(degrees)

2.0

In [60]:
coefficients = np.split(b.data, b.indptr[1:-1])

# mean_coefficient = np.mean(coefficients, axis=1)
# std_coefficient = np.std(coefficients, axis=1)
# min_coefficient = np.min(coefficients, axis=1)
# max_coefficient = np.max(coefficients, axis=1)
# sum_norm_abs_coefficient = np.sum(np.abs(coefficients), axis=1)

In [61]:
coefficients = np.split(b.data, b.indptr[1:-1])

In [62]:
coefficients

[array([0.71803898, 0.75373094]),
 array([0.4511002 , 0.94146668]),
 array([0.95508763]),
 array([0.35833639, 0.921038  , 0.0274011 ])]

In [72]:
print(mean_coefficient)
print(std_coefficient)
print(min_coefficient)
print(max_coefficient)
print(sum_norm_abs_coefficient)

[0.87345251 0.71578605 0.6747381  0.36243384]
[0.09903906 0.15981075 0.09079157 0.11519606]
[0.77441345 0.5559753  0.58394653 0.24723777]
[0.97249157 0.8755968  0.76552967 0.4776299 ]
[1.74690502 1.4315721  1.3494762  0.72486767]


In [73]:
np.column_stack(
    (
        mean_coefficient,
        std_coefficient,
        min_coefficient,
        max_coefficient,
        sum_norm_abs_coefficient,
    )
).shape


(4, 5)

In [74]:
scipy.sparse.csr_matrix(dummy).getnnz(axis=0)

array([2, 3, 2, 1])

In [75]:
c = b.tocsc()

In [76]:
print(c.toarray())

[[0.71803898 0.75373094 0.         0.        ]
 [0.4511002  0.94146668 0.         0.        ]
 [0.         0.         0.95508763 0.        ]
 [0.         0.35833639 0.921038   0.0274011 ]]


In [77]:
c.indices

array([0, 1, 0, 1, 3, 2, 3, 3], dtype=int32)

In [68]:
c.indptr

array([0, 2, 5, 7, 8], dtype=int32)

In [69]:
np.split(c.data, c.indptr[1:-1])

[array([0.71803898, 0.4511002 ]),
 array([0.75373094, 0.94146668, 0.35833639]),
 array([0.95508763, 0.921038  ]),
 array([0.0274011])]

In [79]:
non_zero_cons_for_var = np.split(c.indices, c.indptr[1:-1])

In [78]:
degrees[]

array([2, 2, 1, 3], dtype=int32)